
# =====================================
# Flask App
# =====================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sahar449/DevOps_infra_aws.git
    targetRevision: HEAD
    path: ArgoCD/myChart/helm_chart
    helm:
      releaseName: flask-app
      values: |
        app:
          image:
            repository: 634647866665.dkr.ecr.us-west-2.amazonaws.com/eksdemo
            tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
